### ISSUE TITLE
Showing NaN on the place order page

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#11]
Showing NaN on the place order page
![IMG_20190701_224842](https://user-images.githubusercontent.com/20434469/60454800-74a91480-9c52-11e9-8e8b-5ca33aeaf0b5.jpg)

**Comment by Vaishu5** [comment]
still not working. by default set quantity 1 when user selects any item. So this issue will not occur. And also it does not make sense to keep the quantity 0 when user has selected that item.

**Comment by kadamroshan167** [comment]
hi @Vaishu5 please have look at this

**Comment by Vaishu5** [comment]
Working
