### ISSUE TITLE
Shows empty row on dashboard

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#25]
only token no is visible everything else is hidden.

**Comment by Vaishu5** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/20434469/60756649-a1c44100-a01d-11e9-99f5-18a4af6c4a33.png)

**Comment by Vaishu5** [comment]
happened one time only, after that it worked

**Comment by amitvishwakarma2496** [comment]
![image](https://user-images.githubusercontent.com/20126570/61174295-c4290200-a5bb-11e9-8149-aaeb8ecffe8a.png)
Now it is working fine.

**Comment by Vaishu5** [comment]
working
