### ISSUE TITLE
User should able to login by pressing enter key.

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#26]
In most of the web apps we just fill the credentials and press enter to submit/login without manually pressing the (submit/login) button. It saves the user's time & its convinient for the user also.  This is not working in our login screen. Whenever user fills credentials press the enter key login function should be call.

**Comment by amitvishwakarma2496** [comment]
I have added the functionality of login by pressing enter key and it is working now.

**Comment by Vaishu5** [comment]
Working now.
