### ISSUE TITLE
Filter icon not showing filter options on dashboard

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#30]
On click of filter icon nothing happens on dashboard page. same icon on kitchen page shows the filter options but nothing on the dashboard.
![Screenshot (14)](https://user-images.githubusercontent.com/20434469/60770553-bd9d1500-a0f9-11e9-8f17-d36cc67c8221.png)

**Comment by amitvishwakarma2496** [comment]
It has resolved.

**Comment by Vaishu5** [comment]
Working
