### ISSUE TITLE
Total order count not matching the (count of Placed orders + count of rejected orders)

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#31]
If total orders are 150, then addition of placed orders and rejected orders count should be 150. As checked in db there are 143 placed orders and 7 rejected orders.
![Screenshot (15)](https://user-images.githubusercontent.com/20434469/60771502-c8aa7200-a106-11e9-8aa0-ad7151bda538.png)

**Comment by amitvishwakarma2496** [comment]
Now all counts and total cost on the dashboard page are in sync with orders.
![image](https://user-images.githubusercontent.com/20126570/61176547-38759c80-a5e0-11e9-88d5-4c15c8234ba6.png)

**Comment by Vaishu5** [comment]
Working
