### ISSUE TITLE
Is advertisement of senior designer is necessary?

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#32]
Why we are advertising senior designer in our website or we are going to show something different afterwards their?

**Comment by Vaishu5** [comment]
Also it has shown three times 
![Screenshot (15)](https://user-images.githubusercontent.com/20434469/60771619-62beea00-a108-11e9-86af-e266c95eb8ab.png)

**Comment by amitvishwakarma2496** [comment]
As I told you we are using template therefore those unnecessary div's are there. We will replace those with different types of chart and functionality.

**Comment by Vaishu5** [comment]
Fine
