### ISSUE TITLE
Place Order - Place button is clickable even if already pressed.

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#37]
But should be disable when user has pressed it till we get any response from the server. Right now user can click it any times. Duplicate data will get generated due to this in the database. Also provide the loader till we get any response from the server. Also user is able to place order even if total order cost is NaN.
![Screenshot (131)](https://user-images.githubusercontent.com/20434469/60835705-738f5e80-a1e1-11e9-8486-b5a6f1adf04d.png)

**Comment by amitvishwakarma2496** [comment]
I have resolved this issue. Now I'm hiding filter model on place button click and showing loader until order is not placed.
![image](https://user-images.githubusercontent.com/20126570/61174267-6f858700-a5bb-11e9-8b3a-8ec9915f9a13.png)

**Comment by Vaishu5** [comment]
Correct you are hiding it, but I can open it again place the same order again. Also make the all the fields empty so even if user opens it again he cannot see the previous data. See the screenshot, I have placed the same order twice. Table No : 112
![Screenshot (137)](https://user-images.githubusercontent.com/20434469/61235281-c8d3ee80-a752-11e9-945b-7bec12d80e78.png)

**Comment by kadamroshan167** [comment]
He @Vaishu5 i have disable place button after placing order please have look.

**Comment by Vaishu5** [comment]
Working
