### ISSUE TITLE
What does reset token do?

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#4]
There is Reset Token button in the website. What does it mean?

**Comment by amitvishwakarma2496** [comment]
Reset token functionality is used to reset restaurant token allocated to users from any number to 0.

**Scenario**: Restaurant A having 500 customers per day so they will have more than 500 token allocated to customer on single day. For the next restaurant owner can reset token to zero so it will start allocating token from 1 to all new visitors.

**Comment by Vaishu5** [comment]
I would like to know the need of this functionality. Do we are going to charge restaurants per token?

**Comment by Vaishu5** [comment]
Understood. Explained by manoj.
