### ISSUE TITLE
Databoard - When all orders are rejected or total cost is zero it shown empty

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#44]
Show zero instead of empty
![Screenshot (144)](https://user-images.githubusercontent.com/20434469/61238241-df317880-a759-11e9-9209-7ef46bfdb526.png)

**Comment by kadamroshan167** [comment]
Hi @Vaishu5 please have look at this issues which has been resolved

**Comment by amitvishwakarma2496** [comment]
![image](https://user-images.githubusercontent.com/20126570/61576408-6171c200-aaf7-11e9-871c-da65f7433e58.png)
Now we are showing zero if there is no order.

**Comment by Vaishu5** [comment]
Working
