### ISSUE TITLE
When filtered orders, filter dropdown selected option gets reset to default option. 

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#8]
When selected order status/payment status/table no to filter it shows filtered records but dropdown of corresponding filter gets reset to ""Select order status"" and ""select payment status"". It should show whatever slected by the restaurant manager.

**Comment by kadamroshan167** [comment]
Hi @Vaishu5 please have look at this issue which has been resolve

**Comment by Vaishu5** [comment]
Working
