### ISSUE TITLE
Order updates by pressing enter on dropdowns option. 

### ISSUE THREAD

**Issue by Vaishu5** [mili-technologies/mili-website#9]
User doesnt understand that order gets updated by selecting the status and pressing enter button. it should update on change of dropdown option.

**Comment by amitvishwakarma2496** [comment]
Could you explain this issue in more detail with Screenshot.
According to my understand I made some changes on orders page where on dropdown select pop-up will be shown to user that order placed or rejected.

![image](https://user-images.githubusercontent.com/20126570/61175528-c6e12280-a5ce-11e9-9a1a-9040faa76756.png)

**Comment by Vaishu5** [comment]
Working
